// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDauLVaHJO-bHnoCebVqBo8XeDhXqD6Ib0',
    appId: '1:485696735216:web:9c28ca223ec1cd88a9bf35',
    messagingSenderId: '485696735216',
    projectId: 'logiclubquizapp',
    authDomain: 'logiclubquizapp.firebaseapp.com',
    storageBucket: 'logiclubquizapp.firebasestorage.app',
    measurementId: 'G-66L925Y80S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzEvZy9qb8egQBKabodltRGaTQRj5rFXw',
    appId: '1:485696735216:android:c369ab74ee0924afa9bf35',
    messagingSenderId: '485696735216',
    projectId: 'logiclubquizapp',
    storageBucket: 'logiclubquizapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_HV6CRvOV_X32EV-6y1pvyeArdudJRxA',
    appId: '1:485696735216:ios:8ade3a8924f43d26a9bf35',
    messagingSenderId: '485696735216',
    projectId: 'logiclubquizapp',
    storageBucket: 'logiclubquizapp.firebasestorage.app',
    iosBundleId: 'com.example.logiclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_HV6CRvOV_X32EV-6y1pvyeArdudJRxA',
    appId: '1:485696735216:ios:8ade3a8924f43d26a9bf35',
    messagingSenderId: '485696735216',
    projectId: 'logiclubquizapp',
    storageBucket: 'logiclubquizapp.firebasestorage.app',
    iosBundleId: 'com.example.logiclub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDauLVaHJO-bHnoCebVqBo8XeDhXqD6Ib0',
    appId: '1:485696735216:web:f1a34ef0f6b1b492a9bf35',
    messagingSenderId: '485696735216',
    projectId: 'logiclubquizapp',
    authDomain: 'logiclubquizapp.firebaseapp.com',
    storageBucket: 'logiclubquizapp.firebasestorage.app',
    measurementId: 'G-LH90424VDX',
  );
}
